{{- if not .Values.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics-agent.fullname" . }}
  labels:
    {{- include "metrics-agent.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  CLOUDABILITY_API_KEY: {{ .Values.apiKey | b64enc | quote }}
{{- end }}